{
 "title": "Mini Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage (Namespace,Pod,Servcie)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{namespace}},{{pod}},{{service}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Namespace,Pod,Service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_memory_working_set_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{namespace}},{{pod}},{{service}}"
    }
   ]
  },
  {
   "title": "HTTP Request/Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(http_requests_total{namespace=~\"$namespace\",pod=~\"$pod\"}[30s])) by (namespace,pod,code)",
     "legendFormat": "{{namespace}}.{{pod}}.{{code}}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "kube_pod_status_ready{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}.{{pod}}"
    }
   ]
  }
 ]
}