apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: {{ .Values.namespaces.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: {{ .Values.authService.image }}
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: {{ .Values.authService.resources.requests.memory }}
              cpu: {{ .Values.authService.resources.requests.cpu }}
            limits:
              memory: {{ .Values.authService.resources.limits.memory }}
              cpu: {{ .Values.authService.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80