apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Values.namespaces.app }}
spec:
  selector:
    app: auth-service
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP