apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: {{ .Values.namespaces.system }}
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
