apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minio-secret-reader
  namespace: {{ .Values.namespaces.app }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["minio-creds"]
    verbs: ["get"]