apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minio-secret-reader-binding
  namespace: {{ .Values.namespaces.app }}
subjects:
  - kind: ServiceAccount
    name: data-service-sa
    namespace: {{ .Values.namespaces.app }}
roleRef:
  kind: Role
  name: minio-secret-reader
  apiGroup: rbac.authorization.k8s.io